<h1>Lista de CLientes</h1>

<a class="btn btn-success" title="Novo"
	href="<?php/* echo $this->url('cliente',
     array(	'controller' => 'ClienteController',
							'action'=>'add'
     		)); */?>"> 
     <span class="glyphicon glyphicon-plus"></span>
</a>
<table class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th>Id</th>
			<th>Nome</th>
			<th>Email</th>
			<th>Telefone</th>
			<th>Setor</th>
		</tr>
	</thead>
	<tbody>

		<?php foreach($this->home as $entity): ?>
		<tr>
			<td><?php echo $this->escapeHtml($entity->getId()); ?></td>
			<td><?php echo $this->escapeHtml($entity->getNome()); ?></td>
			<td><?php echo $this->escapeHtml($entity->getEmail()); ?></td>
			<td><?php echo $this->escapeHtml($entity->getTelefone()); ?></td>
			<td><?php echo $this->escapeHtml($entity->getSetor()); ?></td>

		</tr>
		<?php endforeach;?>
	</tbody>
</table>
